language: python
install: pip3 install .
script: python -m unittest discover -p test_*.py
jobs:
  include:
    - name: "Python 3.8 on Linux, generate test coverage"
      python: 3.8
      before_install:
        - sudo apt-get install xclip
        - sudo apt-get install xvfb
        - pip3 install codecov
        - pip3 install flake8
      after_success: codecov
      stage: test
      script: xvfb-run coverage run --source refinery run-tests.py
    - name: "Deploy To Test PyPi"
      python: 3.8
      stage: deploy
      script: git fetch master
      deploy:
        server: https://test.pypi.org/legacy/
        provider: pypi
        user: "__token__"
        password: $PYPI_TOKEN
        distributions: "sdist bdist_wheel"
        skip_existing: true
        on:
          branch: backend
          condition: $(git describe --exact-match --tags master || echo UNREFINED) != "UNREFINED"